---
- hosts: all
  become: yes
  vars_files:
    - vault.yml
  vars:
    timezone: UTC
    sys_packages:
      - build-essential
      - aptitude
      - libpq-dev
      - libxml2-dev
      - libxslt1-dev
      - nodejs
      - curl
      - git-core
      - software-properties-common
      - pgbouncer
      - docutils-common
      - cmake
      - logrotate
      - libicu-dev
      - pkg-config
      - postgresql-client
      - libcurl4-openssl-dev
      - libssl-dev
      - ruby
      - ruby-dev
    logrotate_scripts:
      - name: rails
        path: "/var/www/librariesio/current/log/*.log"
        options:
          - daily
          - rotate 7
          - copytruncate
          - compress
          - delaycompress
          - missingok
          - notifempty
  roles:
    - init
    - rails
    - pgbouncer
    - nickhammond.logrotate
